### ISSUE TITLE
2.5.2 - release note tracking

### ISSUE THREAD

**Issue by cbarcl01** [cidgoh/CanCOGeN_Contextual_Data_Specification#4]
## Specification Changes:

| Field | Change |
| --- | --- |
| `sample collected by` | New picklist IDs |
| `sequence submitted by` | New picklist IDs |

### Version Tracking:
Excel Template, Reference Guides, Curation SOP

x = 2 = No field changes
y = 5 = New picklist IDs
z = 2 = Syntax issues resolved

New Term SOP N/A unless indicated.

## Template To-Dos
- [ ] Update picklist value labels/IDs/descriptions
  - [ ] DataHarmonizer Template ([enums](https://docs.google.com/spreadsheets/d/1jPQAIJcL_xa3oBVFEsYRGLGf7ESTOwzsTSjKZ-0CTYE/edit?gid=819554348#gid=819554348))
- [ ] Update field labels/IDs/descriptions
  - [ ] DataHarmonizer Template ([slots](https://docs.google.com/spreadsheets/d/1jPQAIJcL_xa3oBVFEsYRGLGf7ESTOwzsTSjKZ-0CTYE/edit?gid=951206200#gid=951206200))

**Comment by cbarcl01** [comment]
#1 and #2 sample collected by new picklist terms St. Joseph’s Healthcare Hamilton and Kingston Health Sciences Centre

**Comment by cbarcl01** [comment]
#3 sequence submitted by new term Ontario COVID-19 Genomic Network

**Comment by cbarcl01** [comment]
[Issue 19 on PGP](https://github.com/cidgoh/pathogen-genomics-package/issues/19) - syntax errors

**Comment by cbarcl01** [comment]
Closed with release version [2.5.2](https://github.com/cidgoh/CanCOGeN_Contextual_Data_Specification/tree/v2.5.2)
